devise-authentication/devise-single-page-app/config/routes.rb
Rails.application.routes.draw do
  resources :bikes, constraints: ->(request){ !request.format.html? }
  devise_for :users

  get '*path', to: 'pages#protected', constraints: ->(request){ request.format.html? }
  root to: 'pages#unprotected'
end

devise-authentication/devise-single-page-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

devise-authentication/devise-single-page-app/app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
end

devise-authentication/devise-single-page-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bikes
end

devise-authentication/devise-single-page-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

devise-authentication/devise-single-page-app/app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = current_user.bikes.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:brand, :model_year, :model, :user_id)
    end
end

devise-authentication/devise-single-page-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :protected

  def unprotected
  end

  def protected
  end
end

devise-authentication/devise-single-page-app/app/helpers/application_helper.rb
module ApplicationHelper
end

devise-authentication/devise-single-page-app/app/helpers/bikes_helper.rb
module BikesHelper
end

devise-authentication/devise-single-page-app/app/helpers/pages_helper.rb
module PagesHelper
end

devise-authentication/devise-single-page-app/app/views/bikes/_form.html.erb
<%= form_with(model: bike, local: true) do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model_year %>
    <%= form.number_field :model_year %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

devise-authentication/devise-single-page-app/app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

devise-authentication/devise-single-page-app/app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bikes</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model year</th>
      <th>Model</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.brand %></td>
        <td><%= bike.model_year %></td>
        <td><%= bike.model %></td>
        <td><%= bike.user_id %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

devise-authentication/devise-single-page-app/app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Back', bikes_path %>

devise-authentication/devise-single-page-app/app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @bike.brand %>
</p>

<p>
  <strong>Model year:</strong>
  <%= @bike.model_year %>
</p>

<p>
  <strong>Model:</strong>
  <%= @bike.model %>
</p>

<p>
  <strong>User:</strong>
  <%= @bike.user_id %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>

devise-authentication/devise-single-page-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

devise-authentication/devise-single-page-app/app/views/pages/protected.html.erb
<%= react_component('AuthenticatedApp') %>

devise-authentication/devise-single-page-app/app/views/pages/unprotected.html.erb
<%= react_component('UnauthenticatedApp') %>